[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.18"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
